### ISSUE TITLE
[BE] Spring Batch 스케줄러를 사용한 자동 API 크롤링

### ISSUE THREAD

**Issue by sigridjineth** [codesquad-member-2020/dust-4#27]
## 기술 스택
* Quartz + Spring Batch
* MariaDB
* AWS EC2 Amazon Linux instance

## 스케줄
* Spring Batch에 대해 학습할 러닝 커브가 있는데, 당장 내일까지 구현은 어려울 것으로 보임
* 주말에 시간을 내서 개인적으로 공부해보고 구현하는 것을 목표로 한다.

**Comment by realsigridjin** [comment]
주말에 시간을 내서 개인 저장소로 포크한 다음 작업해본다.
