### ISSUE TITLE
간단 리뷰

### ISSUE THREAD

**Issue by honux77** [codesquad-member-2020/dust-4#30]
## 첫 화면이 너무 깔끔

- 리드미에 프로젝트 관련 내용을 채울 것
- 기본 브랜치를 활성화된 브랜치로 지정 

## 기타

- PR의 수가 커밋수보다 작아 보임
- 협업 상태는 양호해 보이는데 찾아가기가 쉽지 않음

**Comment by honux77** [comment]
이슈를 좀 더 깔끔하게 정리하기

**Comment by realsigridjin** [comment]
@honux77 README.md 업데이트 완료했습니다. 피드백 부탁드립니다 ^^

**Comment by realsigridjin** [comment]
@honux77 저장소에 setting 메뉴가 없는데요. 혹시 어떻게 해야 default branch를 바꿀 수 있을까요?
